name: furqan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  animated_text_kit: ^4.2.2
  animated_theme_switcher: ^2.0.10
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^5.2.1
  bloc: ^8.1.2
  confetti: ^0.8.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  dio: ^5.3.2
  dot_navigation_bar: ^1.0.2
  equatable: ^2.0.7
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^6.0.0
  flutter_facebook_auth: ^7.1.2
  flutter_floating_bottom_bar: ^1.3.0
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get: ^4.7.2
  get_it: ^8.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.18.1
  json_annotation: ^4.9.0
  just_audio: ^0.9.36
  lottie: ^2.7.0
  package_info_plus: ^8.3.1
  page_transition: ^2.2.1
  provider: ^6.1.1
  retrofit: ^4.7.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  supabase_flutter: ^2.10.2
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter  
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/imgs/
    - .env
  # example:
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
